// <auto-generated />
using CoffeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeShop.Migrations
{
    [DbContext(typeof(CoffeeshopDbContext))]
    [Migration("20260525091145_UpdateDetail")]
    partial class UpdateDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=815",
                            IsTrendingProduct = true,
                            Name = "Black Diamond Coffee",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "",
                            ImageUrl = "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=815",
                            IsTrendingProduct = true,
                            Name = "The Roasted Bean",
                            Price = 35m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "",
                            ImageUrl = "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=815",
                            IsTrendingProduct = true,
                            Name = "Beanery Espresso",
                            Price = 45m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "",
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=815",
                            IsTrendingProduct = false,
                            Name = "Americano",
                            Price = 25m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "",
                            ImageUrl = "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=815",
                            IsTrendingProduct = false,
                            Name = "Mocha",
                            Price = 35m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "",
                            ImageUrl = "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=815",
                            IsTrendingProduct = false,
                            Name = "French Press",
                            Price = 55m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
