// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coffeeshop.Data;

#nullable disable

namespace CoffeShop.Migrations
{
    [DbContext(typeof(CoffeeshopDbContext))]
    partial class CoffeeshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coffeeshop.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://link-anh-1.jpg",
                            IsTrendingProduct = false,
                            Name = "America",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://link-anh-2.jpg",
                            IsTrendingProduct = false,
                            Name = "Vietnam",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://link-anh-3.jpg",
                            IsTrendingProduct = false,
                            Name = "United Kingdom",
                            Price = 15m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
